14 us as a user i want to have a match history
cnstll/ft_transcendAnce pull request #142
Opened 2022-11-04 23:54 UTC by llescure

# Description

Match history is available on current user profile
Match history is available on other users profile
Stats info is available on current user profile
Stats info is available on other users profile
Elo info and ranking added to users profile

# Changes include

- [X] New feature (non-breaking change that adds functionality)
- [ ] Bugfix (non-breaking change that solves an issue)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to an issue
- [X] I have linked this PR to a milestone
- [X] I have linked this PR to a project
- [X] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

2022-11-05 18:50 UTC, cnstll requested changes

2022-11-05 18:50 UTC, cnstll commented on backend/app/src/user/user.service.ts
> +        if (matchesList[i].p1s == 10) matchWon = true;
en cas d'abandon en cours de partie, on pourrait avoir des scores de 5 - 2 avec un `matchWon = false` pour les 2 joueurs. Le score est set à 10 automatiquement ? Sinon pourquoi ne pas comparer les 2 scores ?

2022-11-05 18:50 UTC, cnstll commented on backend/app/src/user/user.service.ts
> +  async getUserRanking(userNickname: string) {
Un bloc `try-catch` pour cette fonciton pourrait-être pertinent non ? pareil pour la fonction `getUsersMatchHistory`

2022-11-05 18:50 UTC, cnstll commented on frontend/app/src/components/section-components/profile/stats-box.tsx
>    return (
Bug de décompte des W/L sur la stat box ?
![image](https://user-images.githubusercontent.com/67589684/200135264-588a09f6-6be0-40e9-9fbc-6a9f1d61faed.png)

2022-11-05 18:50 UTC, cnstll commented on frontend/app/src/components/section-components/search-box.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
Petit soucis d'update quand je passe de mon profil au profil d'un autre user en via la search box (cf screenshots)

2022-11-05 18:50 UTC, cnstll commented on frontend/app/src/components/section-components/search-box.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
![image](https://user-images.githubusercontent.com/67589684/200135826-b6f8ff71-bb96-48f1-9cb8-03e397934193.png)

2022-11-05 18:50 UTC, cnstll commented on frontend/app/src/components/section-components/search-box.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
![image](https://user-images.githubusercontent.com/67589684/200136104-5b4d6551-092e-4bb0-a756-aeb8d5881fa9.png)

2022-11-05 18:50 UTC, cnstll commented on frontend/app/src/components/section-components/search-box.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
Le bug ne se fait qu'en passant de mon profile à un autre profile, mais pas du profile de 2 autres users

2022-11-05 19:02 UTC, cnstll commented on frontend/app/src/components/section-components/profile/stats-box.tsx
>    return (
Lorsqu'aucune partie n'a été jouée par le user, la match history est vide, on pourrait ajouter un message ? (empty state screen)

2022-11-06 21:13 UTC, llescure commented on backend/app/src/user/user.service.ts
> +  async getUserMatches(userNickname: string) {
On utilise le nickname pour avoir le même composant match history pour la personne connectée et les autres users. J'ai fait le test en changeant le nickname ça ne pose pas de problème 👍

2022-11-06 21:15 UTC, llescure commented on backend/app/src/user/user.service.ts
> +        if (matchesList[i].p1s == 10) matchWon = true;
Le score est en effet set automatiquement à 10 en cas d'abandon. Mais il y a un bug pour le moment, c'est le user qui quitte la partie qui gagne et non son adversaire

2022-11-06 21:29 UTC, llescure commented on frontend/app/src/components/section-components/profile/stats-box.tsx
>    return (
Fixed !

2022-11-07 09:58 UTC, llescure commented on backend/app/src/user/user.service.ts
> +  async getUserRanking(userNickname: string) {
Je pense qu'il n'y en a pas besoin pour getUserRanking. Si le user n'a pas de rank une chaine vide est renvoyée. Normalement le user aura forcément un raking car le tri se fait sur le eloscore qui est généré à la création de l'utilisateur.
Pour getUserMatchHistory c'est changé 👍

2022-11-07 10:09 UTC, llescure commented on backend/app/src/user/user.service.ts
> +    const stats: StatDto = {
C'est vrai j'ai changé pour des interfaces

2022-11-07 15:44 UTC, llescure commented on frontend/app/src/components/section-components/search-box.tsx
> +import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
Bug fixed

2022-11-08 09:10 UTC, cnstll approved these changes

2022-11-08 09:12 UTC, merged